default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
<% if ENV["DATABASE_URL"].present? %>
  url: <%= ENV["DATABASE_URL"] %>
<% end %>
  host: <%= ENV["POSTGRES_HOST"] %>
  port: <%= ENV["POSTGRES_PORT"] || 5432 %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>


development:
  <<: *default
  database: <%= ENV["POSTGRES_DB_DEV"] %>

test:
  <<: *default
  database: <%= ENV["POSTGRES_DB_TEST"]%>

production:
  <<: *default
  database: <%= ENV["POSTGRES_DB_PROD"] %>
